# ============================================================================ #
#           S e l e n i u m   G r i d   -   N o d e   -   C h r o m e
# ============================================================================ #
#               H o r i z o n t a l   P o d   A u t o S c a l e r
# ============================================================================ #

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: selenium-node-chrome
  namespace: selenium
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: selenium-node-chrome
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 30